"""macOS application-shell release identity."""
APP_SERIES = "2.0"
APP_BUILD = "6"
APP_PATCH = "0.2"
APP_RELEASE_NAME = "Backend Ownership Hardening"
APP_DISPLAY = f"FFD {APP_SERIES} Build {APP_BUILD}"
APP_RELEASE_DISPLAY = f"FFD {APP_SERIES} Build {APP_BUILD}.{APP_PATCH}"
APP_FULL_NAME = f"Reunion Companion — {APP_RELEASE_DISPLAY} {APP_RELEASE_NAME}"
ENGINE_BASELINE = "FFD 1.9 RC1"
