"""macOS application-shell release identity."""
APP_SERIES = "2.0"
APP_BUILD = "3"
APP_RELEASE_NAME = "Native Application Integration"
APP_DISPLAY = f"FFD {APP_SERIES} Build {APP_BUILD}"
APP_FULL_NAME = f"Reunion Companion — {APP_DISPLAY} {APP_RELEASE_NAME}"
ENGINE_BASELINE = "FFD 1.9 RC1"
